name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches: [ feature-automerge-test ]
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge-release:
    runs-on: ubuntu-latest
    steps:
      - name: automerge-release
        uses: "pascalgn/automerge-action@80acb0f883348dcfd0e526288f7d27a12b9333be"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: automerge-release ## to be used by PS once they are happy that the PR is ready
          MERGE_METHOD: merge
